# DEF --> Default
# DIR --> Directory
# RAW --> settings for the raw dataset
# PROCESSED --> settings for the processed data
# MRK --> marker, i.e. the displayed marker and the color in a plot
# EXP --> Export
PLOT:
    RAW_DATA_LABEL: "Raw Spectrum"
    RAW_DATA_MRK: "r"
    RAW_BASELINE_LABEL: "Baseline"
    RAW_BASELINE_MRK: "b--"
    RAW_X_LABEL: "Pixel"
    RAW_Y_LABEL: "Intensity / a.u."
    PROCESSED_DATA_LABEL: "Processed Spectrum"
    PROCESSED_DATA_MRK: "r"
    PROCESSED_X_LABEL: "Wavelength / nm"
    PROCESSED_Y_LABEL: "Intensity / a.u."
    DEF_LINEWIDTH: 0.5
    DEF_AXIS_COLOR: '0.2'

FILE:
    DEF_DIR: "../ASTERIX1059"
    DEF_FILE: ""


SAVE:
    RAW_APPENDIX: "_raw"
    PROCESSED_APPENDIX: "_processed"
    EXP_SUFFIX: ".csv"
    DEF_BATCH_FILTER: "Comma separated (*.csv)"
    DEF_BATCH_NAME: "_batch"

LOAD:
    VALID_SUFFIX:
        - "csv"
        - "spk"
        - "Spk"
    SUFFIXES:
        - "Data sets (*.spk *.csv)"
        - "SpexHex File (*.spk)"
        - "Exported Raw spectrum (*.csv)"
    VALID_SCHEME:
        - "file"

DIALECT:
    name: "spectral_data"
    delimiter: "\t"
    #csv.QUOTE_MINIMAL = 0
    quoting: 0

MARKER:
    HEADER: "Date"
    DATA: "Data"

DATA_STRUCTURE:
    SPK_DATA_COLUMN: 3
    CSV_DATA_COLUMN: 1

BATCH:
    SUFFIX: "csv"
    SEPARATOR: ":"
    INDEX_FORMAT: "4d"

