BATCH:
  INDEX_FORMAT: 4d
  SEPARATOR: ':'
EXPORT:
  BATCH_FILTER: Comma separated (*.csv)
  DEF_BATCH_NAME: _batch
  SUFFIX: .csv
FILE:
  DEF_DIR: ./sample files
  DEF_FILE: ''
  LOG_FILE: /home/hauke/IAF/oes-spectra-analysis-Homeversion/debug.log
FITTING:
  DIR: ./fittings/
  FILE_PATTERN: fitting.yml
IMPORT:
  SUFFIXES:
  - Data sets (*.spk *.csv *.asc)
  - SpexHex File (*.spk)
  - Exported Raw spectrum (*.csv)
  - Full information spectrum (*.asc)
  VALID_SUFFIX:
  - asc
  - csv
  - spk
  - Spk
PLOT:
  BATCH_DATA_COLOR: k
  BATCH_DATA_LABEL: Characteristic
  BATCH_X_LABEL: Time / h
  BATCH_Y_LABEL: Characteristic / a.u.
  DEF_AXIS_COLOR: '0.2'
  DEF_LINEWIDTH: 0.8
  INT_PEAK_COLOR: g
  INT_REF_COLOR: b
  PROCESSED_DATA_COLOR: r
  PROCESSED_DATA_LABEL: Processed Spectrum
  PROCESSED_X_LABEL: Wavelength / nm
  PROCESSED_Y_LABEL: Intensity / a.u.
  RAW_BASELINE_COLOR: b
  RAW_BASELINE_LABEL: Baseline
  RAW_BASELINE_STYLE: --
  RAW_DATA_COLOR: r
  RAW_DATA_LABEL: Raw Spectrum
  RAW_X_LABEL: Pixel
  RAW_Y_LABEL: Intensity / a.u.
