# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batch_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_batch(object):
    def setupUi(self, batch):
        batch.setObjectName("batch")
        batch.resize(459, 436)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("afm.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        batch.setWindowIcon(icon)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(batch)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.csvfile = QtWidgets.QLineEdit(batch)
        self.csvfile.setReadOnly(True)
        self.csvfile.setObjectName("csvfile")
        self.horizontalLayout_2.addWidget(self.csvfile)
        self.setfilename = QtWidgets.QPushButton(batch)
        self.setfilename.setObjectName("setfilename")
        self.horizontalLayout_2.addWidget(self.setfilename)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.files2analyze = QtWidgets.QListView(batch)
        self.files2analyze.setObjectName("files2analyze")
        self.horizontalLayout_3.addWidget(self.files2analyze)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.browseBtn = QtWidgets.QPushButton(batch)
        self.browseBtn.setEnabled(False)
        self.browseBtn.setObjectName("browseBtn")
        self.verticalLayout_3.addWidget(self.browseBtn)
        self.calcBtn = QtWidgets.QPushButton(batch)
        self.calcBtn.setEnabled(False)
        self.calcBtn.setObjectName("calcBtn")
        self.verticalLayout_3.addWidget(self.calcBtn)
        self.clearBtn = QtWidgets.QPushButton(batch)
        self.clearBtn.setEnabled(False)
        self.clearBtn.setObjectName("clearBtn")
        self.verticalLayout_3.addWidget(self.clearBtn)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(batch)
        self.groupBox.setEnabled(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ChPeakHeight = QtWidgets.QCheckBox(self.groupBox)
        self.ChPeakHeight.setObjectName("ChPeakHeight")
        self.verticalLayout_2.addWidget(self.ChPeakHeight)
        self.ChPeakArea = QtWidgets.QCheckBox(self.groupBox)
        self.ChPeakArea.setObjectName("ChPeakArea")
        self.verticalLayout_2.addWidget(self.ChPeakArea)
        self.ChBaseline = QtWidgets.QCheckBox(self.groupBox)
        self.ChBaseline.setObjectName("ChBaseline")
        self.verticalLayout_2.addWidget(self.ChBaseline)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ChPeakPos = QtWidgets.QCheckBox(self.groupBox)
        self.ChPeakPos.setObjectName("ChPeakPos")
        self.verticalLayout.addWidget(self.ChPeakPos)
        self.ChPeakHeightRaw = QtWidgets.QCheckBox(self.groupBox)
        self.ChPeakHeightRaw.setObjectName("ChPeakHeightRaw")
        self.verticalLayout.addWidget(self.ChPeakHeightRaw)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(batch)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.DispFile = QtWidgets.QLineEdit(self.groupBox_2)
        self.DispFile.setEnabled(False)
        self.DispFile.setReadOnly(True)
        self.DispFile.setObjectName("DispFile")
        self.horizontalLayout_4.addWidget(self.DispFile)
        self.DispSpin = QtWidgets.QSpinBox(self.groupBox_2)
        self.DispSpin.setEnabled(False)
        self.DispSpin.setReadOnly(False)
        self.DispSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.DispSpin.setMinimum(0)
        self.DispSpin.setMaximum(0)
        self.DispSpin.setObjectName("DispSpin")
        self.horizontalLayout_4.addWidget(self.DispSpin)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.progressBar = QtWidgets.QProgressBar(batch)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)

        self.retranslateUi(batch)
        self.DispSpin.valueChanged['int'].connect(self.DispSpin.setValue)
        self.pushButton.clicked.connect(self.ChBaseline.toggle)
        self.pushButton.clicked.connect(self.ChPeakHeight.toggle)
        self.pushButton.clicked.connect(self.ChPeakArea.toggle)
        self.pushButton.clicked.connect(self.ChPeakPos.toggle)
        self.pushButton.clicked.connect(self.ChPeakHeightRaw.toggle)
        QtCore.QMetaObject.connectSlotsByName(batch)

    def retranslateUi(self, batch):
        _translate = QtCore.QCoreApplication.translate
        batch.setWindowTitle(_translate("batch", "Batch Analysis"))
        self.setfilename.setText(_translate("batch", "&Set Filename"))
        self.browseBtn.setText(_translate("batch", "&Browse Files"))
        self.calcBtn.setText(_translate("batch", "&Calculate"))
        self.clearBtn.setText(_translate("batch", "Clear"))
        self.groupBox.setTitle(_translate("batch", "Parameters"))
        self.ChPeakHeight.setText(_translate("batch", "Peak height"))
        self.ChPeakArea.setText(_translate("batch", "Peak area"))
        self.ChBaseline.setText(_translate("batch", "Baseline"))
        self.ChPeakPos.setText(_translate("batch", "Peak Position"))
        self.ChPeakHeightRaw.setText(_translate("batch", "Peak height (not corrected)"))
        self.pushButton.setText(_translate("batch", "Select All"))
        self.groupBox_2.setTitle(_translate("batch", "Display"))

