# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batch_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_batch(object):
    def setupUi(self, batch):
        batch.setObjectName("batch")
        batch.resize(605, 850)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("afm.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        batch.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(batch)
        self.gridLayout.setObjectName("gridLayout")
        self.layoutCSVFile = QtWidgets.QHBoxLayout()
        self.layoutCSVFile.setObjectName("layoutCSVFile")
        self.foutCSV = QtWidgets.QLineEdit(batch)
        self.foutCSV.setReadOnly(True)
        self.foutCSV.setObjectName("foutCSV")
        self.layoutCSVFile.addWidget(self.foutCSV)
        self.btnSetFilename = QtWidgets.QPushButton(batch)
        self.btnSetFilename.setObjectName("btnSetFilename")
        self.layoutCSVFile.addWidget(self.btnSetFilename)
        self.gridLayout.addLayout(self.layoutCSVFile, 0, 0, 1, 2)
        self.listFiles = QtWidgets.QListWidget(batch)
        self.listFiles.setObjectName("listFiles")
        self.gridLayout.addWidget(self.listFiles, 1, 0, 3, 1)
        self.btnClear = QtWidgets.QPushButton(batch)
        self.btnClear.setEnabled(True)
        self.btnClear.setObjectName("btnClear")
        self.BtnFileaction = QtWidgets.QButtonGroup(batch)
        self.BtnFileaction.setObjectName("BtnFileaction")
        self.BtnFileaction.setExclusive(False)
        self.BtnFileaction.addButton(self.btnClear)
        self.gridLayout.addWidget(self.btnClear, 2, 1, 1, 1)
        self.btnBrowse = QtWidgets.QPushButton(batch)
        self.btnBrowse.setEnabled(True)
        self.btnBrowse.setObjectName("btnBrowse")
        self.gridLayout.addWidget(self.btnBrowse, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(batch)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.mplConcentration = MatplotlibWidget(batch)
        self.mplConcentration.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplConcentration.sizePolicy().hasHeightForWidth())
        self.mplConcentration.setSizePolicy(sizePolicy)
        self.mplConcentration.setMinimumSize(QtCore.QSize(311, 330))
        self.mplConcentration.setMaximumSize(QtCore.QSize(9999, 9999))
        self.mplConcentration.setObjectName("mplConcentration")
        self.verticalLayout.addWidget(self.mplConcentration)
        self.gridLayout.addLayout(self.verticalLayout, 5, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 255, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.layoutProcess = QtWidgets.QHBoxLayout()
        self.layoutProcess.setObjectName("layoutProcess")
        self.barProgress = QtWidgets.QProgressBar(batch)
        self.barProgress.setProperty("value", 0)
        self.barProgress.setObjectName("barProgress")
        self.layoutProcess.addWidget(self.barProgress)
        self.radConcentration = QtWidgets.QRadioButton(batch)
        self.radConcentration.setObjectName("radConcentration")
        self.RadProcess = QtWidgets.QButtonGroup(batch)
        self.RadProcess.setObjectName("RadProcess")
        self.RadProcess.addButton(self.radConcentration)
        self.layoutProcess.addWidget(self.radConcentration)
        self.radSpectra = QtWidgets.QRadioButton(batch)
        self.radSpectra.setEnabled(True)
        self.radSpectra.setObjectName("radSpectra")
        self.RadProcess.addButton(self.radSpectra)
        self.layoutProcess.addWidget(self.radSpectra)
        self.radExport = QtWidgets.QRadioButton(batch)
        self.radExport.setChecked(True)
        self.radExport.setObjectName("radExport")
        self.RadProcess.addButton(self.radExport)
        self.layoutProcess.addWidget(self.radExport)
        self.btnCalculate = QtWidgets.QPushButton(batch)
        self.btnCalculate.setEnabled(False)
        self.btnCalculate.setObjectName("btnCalculate")
        self.BtnFileaction.addButton(self.btnCalculate)
        self.layoutProcess.addWidget(self.btnCalculate)
        self.btnCancel = QtWidgets.QPushButton(batch)
        self.btnCancel.setObjectName("btnCancel")
        self.layoutProcess.addWidget(self.btnCancel)
        self.gridLayout.addLayout(self.layoutProcess, 4, 0, 1, 2)

        self.retranslateUi(batch)
        QtCore.QMetaObject.connectSlotsByName(batch)
        batch.setTabOrder(self.btnSetFilename, self.btnBrowse)
        batch.setTabOrder(self.btnBrowse, self.foutCSV)
        batch.setTabOrder(self.foutCSV, self.listFiles)
        batch.setTabOrder(self.listFiles, self.btnClear)

    def retranslateUi(self, batch):
        _translate = QtCore.QCoreApplication.translate
        batch.setWindowTitle(_translate("batch", "Batch Analysis"))
        self.btnSetFilename.setText(_translate("batch", "&Set Filename"))
        self.btnClear.setText(_translate("batch", "Clear"))
        self.btnBrowse.setText(_translate("batch", "&Browse Files"))
        self.pushButton.setText(_translate("batch", "Import Concentration"))
        self.radConcentration.setText(_translate("batch", "Plot Concentration"))
        self.radSpectra.setText(_translate("batch", "Plot Spectra"))
        self.radExport.setText(_translate("batch", "Export"))
        self.btnCalculate.setText(_translate("batch", "&Calculate"))
        self.btnCancel.setText(_translate("batch", "Cancel"))

from ui.matplotlibwidget import MatplotlibWidget
