# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batch_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_batch(object):
    def setupUi(self, batch):
        batch.setObjectName("batch")
        batch.resize(459, 436)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("afm.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        batch.setWindowIcon(icon)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(batch)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.csvfile = QtWidgets.QLineEdit(batch)
        self.csvfile.setReadOnly(True)
        self.csvfile.setObjectName("csvfile")
        self.horizontalLayout_2.addWidget(self.csvfile)
        self.btnSetFilename = QtWidgets.QPushButton(batch)
        self.btnSetFilename.setObjectName("btnSetFilename")
        self.horizontalLayout_2.addWidget(self.btnSetFilename)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.files2analyze = QtWidgets.QListView(batch)
        self.files2analyze.setObjectName("files2analyze")
        self.horizontalLayout_3.addWidget(self.files2analyze)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnBrowse = QtWidgets.QPushButton(batch)
        self.btnBrowse.setEnabled(True)
        self.btnBrowse.setObjectName("btnBrowse")
        self.verticalLayout_3.addWidget(self.btnBrowse)
        self.btnCalculate = QtWidgets.QPushButton(batch)
        self.btnCalculate.setEnabled(False)
        self.btnCalculate.setObjectName("btnCalculate")
        self.BtnFileaction = QtWidgets.QButtonGroup(batch)
        self.BtnFileaction.setObjectName("BtnFileaction")
        self.BtnFileaction.setExclusive(False)
        self.BtnFileaction.addButton(self.btnCalculate)
        self.verticalLayout_3.addWidget(self.btnCalculate)
        self.btnClear = QtWidgets.QPushButton(batch)
        self.btnClear.setEnabled(False)
        self.btnClear.setObjectName("btnClear")
        self.BtnFileaction.addButton(self.btnClear)
        self.verticalLayout_3.addWidget(self.btnClear)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(batch)
        self.groupBox.setEnabled(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ChPeakHeight = QtWidgets.QCheckBox(self.groupBox)
        self.ChPeakHeight.setObjectName("ChPeakHeight")
        self.BtnParameters = QtWidgets.QButtonGroup(batch)
        self.BtnParameters.setObjectName("BtnParameters")
        self.BtnParameters.setExclusive(False)
        self.BtnParameters.addButton(self.ChPeakHeight)
        self.verticalLayout_2.addWidget(self.ChPeakHeight)
        self.ChPeakArea = QtWidgets.QCheckBox(self.groupBox)
        self.ChPeakArea.setObjectName("ChPeakArea")
        self.BtnParameters.addButton(self.ChPeakArea)
        self.verticalLayout_2.addWidget(self.ChPeakArea)
        self.ChBaseline = QtWidgets.QCheckBox(self.groupBox)
        self.ChBaseline.setObjectName("ChBaseline")
        self.BtnParameters.addButton(self.ChBaseline)
        self.verticalLayout_2.addWidget(self.ChBaseline)
        self.ChPeakPos = QtWidgets.QCheckBox(self.groupBox)
        self.ChPeakPos.setObjectName("ChPeakPos")
        self.BtnParameters.addButton(self.ChPeakPos)
        self.verticalLayout_2.addWidget(self.ChPeakPos)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ChHead = QtWidgets.QCheckBox(self.groupBox)
        self.ChHead.setObjectName("ChHead")
        self.BtnParameters.addButton(self.ChHead)
        self.verticalLayout.addWidget(self.ChHead)
        self.ChPeakHeightRaw = QtWidgets.QCheckBox(self.groupBox)
        self.ChPeakHeightRaw.setObjectName("ChPeakHeightRaw")
        self.BtnParameters.addButton(self.ChPeakHeightRaw)
        self.verticalLayout.addWidget(self.ChPeakHeightRaw)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btnSelectAll = QtWidgets.QPushButton(self.groupBox)
        self.btnSelectAll.setObjectName("btnSelectAll")
        self.verticalLayout.addWidget(self.btnSelectAll)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupDisplay = QtWidgets.QGroupBox(batch)
        self.groupDisplay.setMinimumSize(QtCore.QSize(0, 0))
        self.groupDisplay.setObjectName("groupDisplay")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupDisplay)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.DispFile = QtWidgets.QLineEdit(self.groupDisplay)
        self.DispFile.setEnabled(False)
        self.DispFile.setReadOnly(True)
        self.DispFile.setObjectName("DispFile")
        self.horizontalLayout_4.addWidget(self.DispFile)
        self.DispSpin = QtWidgets.QSpinBox(self.groupDisplay)
        self.DispSpin.setEnabled(False)
        self.DispSpin.setReadOnly(False)
        self.DispSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.DispSpin.setMinimum(0)
        self.DispSpin.setMaximum(0)
        self.DispSpin.setObjectName("DispSpin")
        self.horizontalLayout_4.addWidget(self.DispSpin)
        self.verticalLayout_4.addWidget(self.groupDisplay)
        self.progressBar = QtWidgets.QProgressBar(batch)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)

        self.retranslateUi(batch)
        self.DispSpin.valueChanged['int'].connect(self.DispSpin.setValue)
        QtCore.QMetaObject.connectSlotsByName(batch)
        batch.setTabOrder(self.btnSetFilename, self.btnBrowse)
        batch.setTabOrder(self.btnBrowse, self.btnSelectAll)
        batch.setTabOrder(self.btnSelectAll, self.btnCalculate)
        batch.setTabOrder(self.btnCalculate, self.ChPeakHeight)
        batch.setTabOrder(self.ChPeakHeight, self.ChPeakArea)
        batch.setTabOrder(self.ChPeakArea, self.ChBaseline)
        batch.setTabOrder(self.ChBaseline, self.ChPeakPos)
        batch.setTabOrder(self.ChPeakPos, self.ChHead)
        batch.setTabOrder(self.ChHead, self.ChPeakHeightRaw)
        batch.setTabOrder(self.ChPeakHeightRaw, self.DispSpin)
        batch.setTabOrder(self.DispSpin, self.csvfile)
        batch.setTabOrder(self.csvfile, self.DispFile)
        batch.setTabOrder(self.DispFile, self.files2analyze)
        batch.setTabOrder(self.files2analyze, self.btnClear)

    def retranslateUi(self, batch):
        _translate = QtCore.QCoreApplication.translate
        batch.setWindowTitle(_translate("batch", "Batch Analysis"))
        self.btnSetFilename.setText(_translate("batch", "&Set Filename"))
        self.btnBrowse.setText(_translate("batch", "&Browse Files"))
        self.btnCalculate.setText(_translate("batch", "&Calculate"))
        self.btnClear.setText(_translate("batch", "Clear"))
        self.groupBox.setTitle(_translate("batch", "Parameters"))
        self.ChPeakHeight.setText(_translate("batch", "Peak height"))
        self.ChPeakArea.setText(_translate("batch", "Peak area"))
        self.ChBaseline.setText(_translate("batch", "Baseline"))
        self.ChPeakPos.setText(_translate("batch", "Peak Position"))
        self.ChHead.setText(_translate("batch", "Header info"))
        self.ChPeakHeightRaw.setText(_translate("batch", "Peak height (not corrected)"))
        self.btnSelectAll.setText(_translate("batch", "Select All"))
        self.groupDisplay.setTitle(_translate("batch", "Display"))

