# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.setWindowModality(QtCore.Qt.NonModal)
        main.resize(1055, 850)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main.sizePolicy().hasHeightForWidth())
        main.setSizePolicy(sizePolicy)
        main.setMinimumSize(QtCore.QSize(540, 850))
        main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        main.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../gfx/dispersion.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main.setWindowIcon(icon)
        main.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(main)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 1041, 791))
        self.layoutWidget.setObjectName("layoutWidget")
        self.layoutGeneral = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.layoutGeneral.setContentsMargins(0, 0, 0, 0)
        self.layoutGeneral.setObjectName("layoutGeneral")
        self.layoutPlot = QtWidgets.QVBoxLayout()
        self.layoutPlot.setObjectName("layoutPlot")
        self.layoutFilename = QtWidgets.QHBoxLayout()
        self.layoutFilename.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layoutFilename.setObjectName("layoutFilename")
        self.lblFilename = QtWidgets.QLabel(self.layoutWidget)
        self.lblFilename.setObjectName("lblFilename")
        self.layoutFilename.addWidget(self.lblFilename)
        self.toutFilename = QtWidgets.QLineEdit(self.layoutWidget)
        self.toutFilename.setReadOnly(True)
        self.toutFilename.setObjectName("toutFilename")
        self.layoutFilename.addWidget(self.toutFilename)
        self.btnFileOpen = QtWidgets.QPushButton(self.layoutWidget)
        self.btnFileOpen.setObjectName("btnFileOpen")
        self.layoutFilename.addWidget(self.btnFileOpen)
        self.layoutPlot.addLayout(self.layoutFilename)
        self.boxRaw = QtWidgets.QGroupBox(self.layoutWidget)
        self.boxRaw.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxRaw.sizePolicy().hasHeightForWidth())
        self.boxRaw.setSizePolicy(sizePolicy)
        self.boxRaw.setMinimumSize(QtCore.QSize(315, 370))
        self.boxRaw.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.boxRaw.setObjectName("boxRaw")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.boxRaw)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mplRaw = MatplotlibWidget(self.boxRaw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplRaw.sizePolicy().hasHeightForWidth())
        self.mplRaw.setSizePolicy(sizePolicy)
        self.mplRaw.setMinimumSize(QtCore.QSize(311, 330))
        self.mplRaw.setMaximumSize(QtCore.QSize(9999, 9999))
        self.mplRaw.setObjectName("mplRaw")
        self.horizontalLayout_4.addWidget(self.mplRaw)
        self.layoutPlot.addWidget(self.boxRaw)
        self.boxProcessed = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxProcessed.sizePolicy().hasHeightForWidth())
        self.boxProcessed.setSizePolicy(sizePolicy)
        self.boxProcessed.setMinimumSize(QtCore.QSize(315, 370))
        self.boxProcessed.setObjectName("boxProcessed")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.boxProcessed)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mplProcessed = MatplotlibWidget(self.boxProcessed)
        self.mplProcessed.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplProcessed.sizePolicy().hasHeightForWidth())
        self.mplProcessed.setSizePolicy(sizePolicy)
        self.mplProcessed.setMinimumSize(QtCore.QSize(310, 330))
        self.mplProcessed.setMaximumSize(QtCore.QSize(9999999, 9999999))
        self.mplProcessed.setObjectName("mplProcessed")
        self.horizontalLayout_5.addWidget(self.mplProcessed)
        self.layoutPlot.addWidget(self.boxProcessed)
        self.layoutGeneral.addLayout(self.layoutPlot)
        spacerItem = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.layoutGeneral.addItem(spacerItem)
        self.layoutInformation = QtWidgets.QVBoxLayout()
        self.layoutInformation.setObjectName("layoutInformation")
        self.boxBasic = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxBasic.sizePolicy().hasHeightForWidth())
        self.boxBasic.setSizePolicy(sizePolicy)
        self.boxBasic.setMinimumSize(QtCore.QSize(183, 0))
        self.boxBasic.setObjectName("boxBasic")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.boxBasic)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblCentralWavelength = QtWidgets.QLabel(self.boxBasic)
        self.lblCentralWavelength.setObjectName("lblCentralWavelength")
        self.verticalLayout.addWidget(self.lblCentralWavelength)
        self.tinCentralWavelength = QtWidgets.QLineEdit(self.boxBasic)
        self.tinCentralWavelength.setInputMask("")
        self.tinCentralWavelength.setReadOnly(False)
        self.tinCentralWavelength.setObjectName("tinCentralWavelength")
        self.verticalLayout.addWidget(self.tinCentralWavelength)
        self.lblGrating = QtWidgets.QLabel(self.boxBasic)
        self.lblGrating.setObjectName("lblGrating")
        self.verticalLayout.addWidget(self.lblGrating)
        self.ddGrating = QtWidgets.QComboBox(self.boxBasic)
        self.ddGrating.setObjectName("ddGrating")
        self.ddGrating.addItem("")
        self.verticalLayout.addWidget(self.ddGrating)
        self.lblFitting = QtWidgets.QLabel(self.boxBasic)
        self.lblFitting.setObjectName("lblFitting")
        self.verticalLayout.addWidget(self.lblFitting)
        self.ddFitting = QtWidgets.QComboBox(self.boxBasic)
        self.ddFitting.setObjectName("ddFitting")
        self.verticalLayout.addWidget(self.ddFitting)
        self.layoutInformation.addWidget(self.boxBasic)
        self.boxResults = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxResults.sizePolicy().hasHeightForWidth())
        self.boxResults.setSizePolicy(sizePolicy)
        self.boxResults.setMinimumSize(QtCore.QSize(183, 0))
        self.boxResults.setObjectName("boxResults")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.boxResults)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblCharacteristicValue = QtWidgets.QLabel(self.boxResults)
        self.lblCharacteristicValue.setEnabled(True)
        self.lblCharacteristicValue.setObjectName("lblCharacteristicValue")
        self.verticalLayout_2.addWidget(self.lblCharacteristicValue)
        self.toutCharacteristicValue = QtWidgets.QLineEdit(self.boxResults)
        self.toutCharacteristicValue.setReadOnly(True)
        self.toutCharacteristicValue.setObjectName("toutCharacteristicValue")
        self.verticalLayout_2.addWidget(self.toutCharacteristicValue)
        self.lblPeakHeight = QtWidgets.QLabel(self.boxResults)
        self.lblPeakHeight.setObjectName("lblPeakHeight")
        self.verticalLayout_2.addWidget(self.lblPeakHeight)
        self.toutPeakHeight = QtWidgets.QLineEdit(self.boxResults)
        self.toutPeakHeight.setReadOnly(True)
        self.toutPeakHeight.setObjectName("toutPeakHeight")
        self.verticalLayout_2.addWidget(self.toutPeakHeight)
        self.lblPeakArea = QtWidgets.QLabel(self.boxResults)
        self.lblPeakArea.setObjectName("lblPeakArea")
        self.verticalLayout_2.addWidget(self.lblPeakArea)
        self.toutPeakArea = QtWidgets.QLineEdit(self.boxResults)
        self.toutPeakArea.setReadOnly(True)
        self.toutPeakArea.setObjectName("toutPeakArea")
        self.verticalLayout_2.addWidget(self.toutPeakArea)
        self.lblBaseline = QtWidgets.QLabel(self.boxResults)
        self.lblBaseline.setObjectName("lblBaseline")
        self.verticalLayout_2.addWidget(self.lblBaseline)
        self.toutBaseline = QtWidgets.QLineEdit(self.boxResults)
        self.toutBaseline.setText("")
        self.toutBaseline.setReadOnly(True)
        self.toutBaseline.setObjectName("toutBaseline")
        self.verticalLayout_2.addWidget(self.toutBaseline)
        self.layoutInformation.addWidget(self.boxResults)
        self.boxFileInforamtion = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxFileInforamtion.sizePolicy().hasHeightForWidth())
        self.boxFileInforamtion.setSizePolicy(sizePolicy)
        self.boxFileInforamtion.setMinimumSize(QtCore.QSize(183, 0))
        self.boxFileInforamtion.setObjectName("boxFileInforamtion")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.boxFileInforamtion)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblDate = QtWidgets.QLabel(self.boxFileInforamtion)
        self.lblDate.setObjectName("lblDate")
        self.verticalLayout_3.addWidget(self.lblDate)
        self.toutDate = QtWidgets.QLineEdit(self.boxFileInforamtion)
        self.toutDate.setReadOnly(True)
        self.toutDate.setObjectName("toutDate")
        self.verticalLayout_3.addWidget(self.toutDate)
        self.lblTime = QtWidgets.QLabel(self.boxFileInforamtion)
        self.lblTime.setObjectName("lblTime")
        self.verticalLayout_3.addWidget(self.lblTime)
        self.toutTime = QtWidgets.QLineEdit(self.boxFileInforamtion)
        self.toutTime.setReadOnly(True)
        self.toutTime.setObjectName("toutTime")
        self.verticalLayout_3.addWidget(self.toutTime)
        self.layoutInformation.addWidget(self.boxFileInforamtion)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layoutInformation.addItem(spacerItem1)
        self.layoutGeneral.addLayout(self.layoutInformation)
        main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSave = QtWidgets.QMenu(self.menuFile)
        self.menuSave.setEnabled(True)
        self.menuSave.setObjectName("menuSave")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main)
        self.statusbar.setObjectName("statusbar")
        main.setStatusBar(self.statusbar)
        self.actOpen = QtWidgets.QAction(main)
        self.actOpen.setObjectName("actOpen")
        self.actRedraw = QtWidgets.QAction(main)
        self.actRedraw.setEnabled(False)
        self.actRedraw.setObjectName("actRedraw")
        self.actQuit = QtWidgets.QAction(main)
        self.actQuit.setObjectName("actQuit")
        self.actOpenBatch = QtWidgets.QAction(main)
        self.actOpenBatch.setObjectName("actOpenBatch")
        self.actSaveRaw = QtWidgets.QAction(main)
        self.actSaveRaw.setObjectName("actSaveRaw")
        self.actSaveProcessed = QtWidgets.QAction(main)
        self.actSaveProcessed.setObjectName("actSaveProcessed")
        self.actionAuthor = QtWidgets.QAction(main)
        self.actionAuthor.setObjectName("actionAuthor")
        self.menuSave.addAction(self.actSaveRaw)
        self.menuSave.addAction(self.actSaveProcessed)
        self.menuFile.addAction(self.actOpen)
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actQuit)
        self.menuTools.addAction(self.actOpenBatch)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(main)
        self.actQuit.triggered.connect(main.close)
        QtCore.QMetaObject.connectSlotsByName(main)
        main.setTabOrder(self.btnFileOpen, self.tinCentralWavelength)
        main.setTabOrder(self.tinCentralWavelength, self.toutPeakHeight)
        main.setTabOrder(self.toutPeakHeight, self.toutPeakArea)
        main.setTabOrder(self.toutPeakArea, self.toutFilename)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "OES-Spectra-Analysis"))
        self.lblFilename.setText(_translate("main", "File:"))
        self.btnFileOpen.setText(_translate("main", "Browse"))
        self.boxRaw.setTitle(_translate("main", "Raw Spectrum"))
        self.boxProcessed.setTitle(_translate("main", "Processed Spectrum"))
        self.boxBasic.setTitle(_translate("main", "Basic Information"))
        self.lblCentralWavelength.setText(_translate("main", "Central Wavelength (nm):"))
        self.tinCentralWavelength.setText(_translate("main", "433"))
        self.lblGrating.setText(_translate("main", "Grating (l/mm):"))
        self.ddGrating.setItemText(0, _translate("main", "2400"))
        self.lblFitting.setText(_translate("main", "Fitting:"))
        self.boxResults.setTitle(_translate("main", "Results"))
        self.lblCharacteristicValue.setText(_translate("main", "Characteristic Value:"))
        self.lblPeakHeight.setText(_translate("main", "Peak Height:"))
        self.lblPeakArea.setText(_translate("main", "Peak Area:"))
        self.lblBaseline.setText(_translate("main", "Baseline:"))
        self.boxFileInforamtion.setTitle(_translate("main", "File Information"))
        self.lblDate.setText(_translate("main", "Date:"))
        self.lblTime.setText(_translate("main", "Time:"))
        self.menuFile.setTitle(_translate("main", "&File"))
        self.menuSave.setTitle(_translate("main", "Save..."))
        self.menuTools.setTitle(_translate("main", "&Tools"))
        self.actOpen.setText(_translate("main", "&Open"))
        self.actRedraw.setText(_translate("main", "&Redraw Curves"))
        self.actQuit.setText(_translate("main", "&Quit"))
        self.actOpenBatch.setText(_translate("main", "Analyze &Multiple Files"))
        self.actSaveRaw.setText(_translate("main", "Raw Data"))
        self.actSaveProcessed.setText(_translate("main", "Fitted result"))
        self.actionAuthor.setText(_translate("main", "Author"))

from ui.matplotlibwidget import MatplotlibWidget
