# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.setWindowModality(QtCore.Qt.NonModal)
        main.resize(1060, 850)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main.sizePolicy().hasHeightForWidth())
        main.setSizePolicy(sizePolicy)
        main.setMinimumSize(QtCore.QSize(540, 850))
        main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        main.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./gfx/dispersion.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main.setWindowIcon(icon)
        main.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(main)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, 9, 1041, 791))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.EdFilename = QtWidgets.QLineEdit(self.widget)
        self.EdFilename.setReadOnly(True)
        self.EdFilename.setObjectName("EdFilename")
        self.horizontalLayout.addWidget(self.EdFilename)
        self.BtFileOpen = QtWidgets.QPushButton(self.widget)
        self.BtFileOpen.setObjectName("BtFileOpen")
        self.horizontalLayout.addWidget(self.BtFileOpen)
        self.BtRedraw = QtWidgets.QPushButton(self.widget)
        self.BtRedraw.setEnabled(False)
        self.BtRedraw.setObjectName("BtRedraw")
        self.horizontalLayout.addWidget(self.BtRedraw)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.raw_2 = QtWidgets.QGroupBox(self.widget)
        self.raw_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raw_2.sizePolicy().hasHeightForWidth())
        self.raw_2.setSizePolicy(sizePolicy)
        self.raw_2.setMinimumSize(QtCore.QSize(315, 370))
        self.raw_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.raw_2.setObjectName("raw_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.raw_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.MplRaw = MatplotlibWidget(self.raw_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MplRaw.sizePolicy().hasHeightForWidth())
        self.MplRaw.setSizePolicy(sizePolicy)
        self.MplRaw.setMinimumSize(QtCore.QSize(311, 330))
        self.MplRaw.setMaximumSize(QtCore.QSize(9999, 9999))
        self.MplRaw.setObjectName("MplRaw")
        self.horizontalLayout_4.addWidget(self.MplRaw)
        self.verticalLayout_4.addWidget(self.raw_2)
        self.fitted_2 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitted_2.sizePolicy().hasHeightForWidth())
        self.fitted_2.setSizePolicy(sizePolicy)
        self.fitted_2.setMinimumSize(QtCore.QSize(315, 370))
        self.fitted_2.setObjectName("fitted_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.fitted_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.MplProcessed = MatplotlibWidget(self.fitted_2)
        self.MplProcessed.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MplProcessed.sizePolicy().hasHeightForWidth())
        self.MplProcessed.setSizePolicy(sizePolicy)
        self.MplProcessed.setMinimumSize(QtCore.QSize(310, 330))
        self.MplProcessed.setMaximumSize(QtCore.QSize(9999999, 9999999))
        self.MplProcessed.setObjectName("MplProcessed")
        self.horizontalLayout_5.addWidget(self.MplProcessed)
        self.verticalLayout_4.addWidget(self.fitted_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(183, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.EdCWavelength = QtWidgets.QLineEdit(self.groupBox)
        self.EdCWavelength.setReadOnly(False)
        self.EdCWavelength.setObjectName("EdCWavelength")
        self.verticalLayout.addWidget(self.EdCWavelength)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.GratingBox = QtWidgets.QComboBox(self.groupBox)
        self.GratingBox.setObjectName("GratingBox")
        self.GratingBox.addItem("")
        self.verticalLayout.addWidget(self.GratingBox)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.FitTypeBox = QtWidgets.QComboBox(self.groupBox)
        self.FitTypeBox.setObjectName("FitTypeBox")
        self.FitTypeBox.addItem("")
        self.verticalLayout.addWidget(self.FitTypeBox)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(183, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.EdPeakHeight = QtWidgets.QLineEdit(self.groupBox_2)
        self.EdPeakHeight.setReadOnly(True)
        self.EdPeakHeight.setObjectName("EdPeakHeight")
        self.verticalLayout_2.addWidget(self.EdPeakHeight)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.EdPeakArea = QtWidgets.QLineEdit(self.groupBox_2)
        self.EdPeakArea.setReadOnly(True)
        self.EdPeakArea.setObjectName("EdPeakArea")
        self.verticalLayout_2.addWidget(self.EdPeakArea)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.EdBaseline = QtWidgets.QLineEdit(self.groupBox_2)
        self.EdBaseline.setText("")
        self.EdBaseline.setReadOnly(True)
        self.EdBaseline.setObjectName("EdBaseline")
        self.verticalLayout_2.addWidget(self.EdBaseline)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(183, 0))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.EdDate = QtWidgets.QLineEdit(self.groupBox_3)
        self.EdDate.setReadOnly(True)
        self.EdDate.setObjectName("EdDate")
        self.verticalLayout_3.addWidget(self.EdDate)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.EdTime = QtWidgets.QLineEdit(self.groupBox_3)
        self.EdTime.setReadOnly(True)
        self.EdTime.setObjectName("EdTime")
        self.verticalLayout_3.addWidget(self.EdTime)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuSave = QtWidgets.QMenu(self.menu_File)
        self.menuSave.setEnabled(False)
        self.menuSave.setObjectName("menuSave")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main)
        self.statusbar.setObjectName("statusbar")
        main.setStatusBar(self.statusbar)
        self.ActionOpen = QtWidgets.QAction(main)
        self.ActionOpen.setObjectName("ActionOpen")
        self.ActionRedraw = QtWidgets.QAction(main)
        self.ActionRedraw.setEnabled(False)
        self.ActionRedraw.setObjectName("ActionRedraw")
        self.ActionQuit = QtWidgets.QAction(main)
        self.ActionQuit.setObjectName("ActionQuit")
        self.ActionAnalyzeMultipleFiles = QtWidgets.QAction(main)
        self.ActionAnalyzeMultipleFiles.setObjectName("ActionAnalyzeMultipleFiles")
        self.ActionSaveRaw = QtWidgets.QAction(main)
        self.ActionSaveRaw.setObjectName("ActionSaveRaw")
        self.ActionSaveProcessed = QtWidgets.QAction(main)
        self.ActionSaveProcessed.setObjectName("ActionSaveProcessed")
        self.actionAuthor = QtWidgets.QAction(main)
        self.actionAuthor.setObjectName("actionAuthor")
        self.menuSave.addAction(self.ActionSaveRaw)
        self.menuSave.addAction(self.ActionSaveProcessed)
        self.menu_File.addAction(self.ActionOpen)
        self.menu_File.addAction(self.ActionRedraw)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.menuSave.menuAction())
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.ActionQuit)
        self.menuTools.addAction(self.ActionAnalyzeMultipleFiles)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(main)
        self.ActionQuit.triggered.connect(main.close)
        self.EdCWavelength.returnPressed.connect(self.BtRedraw.click)
        QtCore.QMetaObject.connectSlotsByName(main)
        main.setTabOrder(self.BtFileOpen, self.EdCWavelength)
        main.setTabOrder(self.EdCWavelength, self.BtRedraw)
        main.setTabOrder(self.BtRedraw, self.EdPeakHeight)
        main.setTabOrder(self.EdPeakHeight, self.EdPeakArea)
        main.setTabOrder(self.EdPeakArea, self.EdFilename)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "OES-Spectra-Analysis"))
        self.label.setText(_translate("main", "File:"))
        self.BtFileOpen.setText(_translate("main", "Browse"))
        self.BtRedraw.setText(_translate("main", "Redraw"))
        self.raw_2.setTitle(_translate("main", "Raw Spectrum"))
        self.fitted_2.setTitle(_translate("main", "Processed Spectrum"))
        self.groupBox.setTitle(_translate("main", "Basic Information"))
        self.label_2.setText(_translate("main", "Central Wavelength (nm):"))
        self.EdCWavelength.setText(_translate("main", "433"))
        self.label_3.setText(_translate("main", "Grating (l/mm):"))
        self.GratingBox.setItemText(0, _translate("main", "2400"))
        self.label_6.setText(_translate("main", "Fitting:"))
        self.FitTypeBox.setItemText(0, _translate("main", "Boron Peak Fitting", "B"))
        self.groupBox_2.setTitle(_translate("main", "Results"))
        self.label_4.setText(_translate("main", "Peak Height:"))
        self.label_5.setText(_translate("main", "Peak Area:"))
        self.label_7.setText(_translate("main", "Baseline:"))
        self.groupBox_3.setTitle(_translate("main", "File Information"))
        self.label_8.setText(_translate("main", "Date:"))
        self.label_9.setText(_translate("main", "Time:"))
        self.menu_File.setTitle(_translate("main", "&File"))
        self.menuSave.setTitle(_translate("main", "Save..."))
        self.menuTools.setTitle(_translate("main", "&Tools"))
        self.ActionOpen.setText(_translate("main", "&Open"))
        self.ActionRedraw.setText(_translate("main", "&Redraw Curves"))
        self.ActionQuit.setText(_translate("main", "&Quit"))
        self.ActionAnalyzeMultipleFiles.setText(_translate("main", "Analyze &Multiple Files"))
        self.ActionSaveRaw.setText(_translate("main", "Raw Data"))
        self.ActionSaveProcessed.setText(_translate("main", "Fitted result"))
        self.actionAuthor.setText(_translate("main", "Author"))

from ui.matplotlibwidget import MatplotlibWidget
