#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Is the layout of the main window with minor extensions to the qt functionality

Created on Fri Jan 27 2020

@author: Hauke Wernecke
"""




# local modules/libs
from ui.ui_main_window import Ui_main

class UIMain(Ui_main):
    """used to extend the normal class, which is generated by qt designer.
    Methods can be added (like set_all) or connections etc can be made without
    handling the normal generated class, which is overridden whenever the gui
    is changed"""
    def __init__(self, parent):
        """

        Parameters
        ----------
        parent : QMainWindow
            The "parent" of this GUI. It is used for connections to other GUIs
            other (rather general) functions.

        Returns
        -------
        None.

        """
        self.parent = parent
        self.setupUi(self.parent)
        # Setup Events
        self.set_connections()


    def set_connections(self):
        """
        set the connections (functions/methods which are executed when
        something is clicked/...

        Returns
        -------
        None.

        """
        # act: option in a dropdown of the menu bar
        # btn : Button
        self.btnFileOpen.clicked.connect(self.parent.file_open)
        self.actOpen.triggered.connect(self.parent.file_open)
        self.actSaveRaw.triggered.connect(self.parent.save_raw)
        self.actSaveProcessed.triggered.connect(self.parent.save_processed)
        self.actOpenBatch.triggered.connect(self.parent.batch.show)
        # Following connection is unneccesary due to handling in closeEvent of AnalysisWindow
        # self.actQuit.triggered.connect(self.parent.batch.close)